apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autospotting
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          tolerations:
          - effect: NoSchedule
            key: dedicated
            operator: Equal
            value: jobs
          nodeSelector:
            dedicated: jobs
          restartPolicy: Never
          containers:
          - name: autospotting-ci
            image: 308882746353.dkr.ecr.us-east-1.amazonaws.com/parkassist/autospotting-ci:latest
            resources:
              requests:
                cpu: 30m
                memory: 30Mi
            envFrom:
            - configMapRef:
                name: autospotting-ci
